version: '3'

services:
  node:
    image: redis:latest
    ports:
      - 6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server ./redis.conf
    networks:
      - redis_network

networks:
  redis_network: